backend:
  name: github
  repo: Contiblu/design-studio-i.github.io
  branch: main 
  base_url: https://gatekeeper.decapcms.org

media_folder: "assets/images/merch"
public_folder: "/assets/images/merch"

collections:
  - name: "merch_sections"
    label: "Категории Мерча"
    files:
      - label: "Аксессуары"
        name: "accessories"
        file: "_data/merch/accessories.yml"
        fields: &product_fields
          - label: "Товары"
            name: "merch"
            widget: "list"
            allow_add: true
            fields:
              - {label: "ID (slug)", name: "slug", widget: "string"}
              - {label: "Название", name: "title", widget: "string"}
              - {label: "Цена (цифры)", name: "price", widget: "string"}
              - {label: "Картинка", name: "image", widget: "image"} 
              - {label: "Описание", name: "description", widget: "text", required: false}

      - label: "Авто-товары"
        name: "auto"
        file: "_data/merch/auto.yml"
        fields: *product_fields

      - label: "Интерьер"
        name: "interior"
        file: "_data/merch/interior.yml"
        fields: *product_fields

      - label: "Одежда"
        name: "clothes"
        file: "_data/merch/clothes.yml"
        fields: *product_fields 

      - label: "Постельное"
        name: "bed_linen"
        file: "_data/merch/bed_linen.yml"
        fields: *product_fields

      - label: "Для бизнеса"
        name: "business"
        file: "_data/merch/business.yml"
        fields: *product_fields

      - label: "Дизайн для вышивальных машин"
        name: "design"
        file: "_data/merch/design.yml"
        fields: *product_fields 

      - label: "Для дома"
        name: "home"
        file: "_data/merch/home.yml"
        fields: *product_fields 

      - label: "Детский мир"
        name: "kids"
        file: "_data/merch/kids.yml"
        fields: *product_fields

      - label: "Игрушки и сувениры"
        name: "toys"
        file: "_data/merch/toys.yml"
        fields: *product_fields
